"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import importlib.util
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# ==========================================
# MODEL CACHE (Marker/HF/Torch) -> simpan di project (drive D)
# ==========================================
_cache_base_raw = os.getenv("RAG_MODEL_CACHE_BASE_DIR", "")
if _cache_base_raw:
    _cache_base_candidate = Path(_cache_base_raw).expanduser()
    RAG_MODEL_CACHE_BASE_DIR = (
        _cache_base_candidate
        if _cache_base_candidate.is_absolute()
        else (BASE_DIR / _cache_base_candidate)
    )
else:
    RAG_MODEL_CACHE_BASE_DIR = BASE_DIR / "model_cache"
RAG_MODEL_CACHE_BASE_DIR.mkdir(parents=True, exist_ok=True)
_hf_cache_dir = RAG_MODEL_CACHE_BASE_DIR / "huggingface"
_torch_cache_dir = RAG_MODEL_CACHE_BASE_DIR / "torch"
_datalab_cache_dir = RAG_MODEL_CACHE_BASE_DIR
_hf_cache_dir.mkdir(parents=True, exist_ok=True)
_torch_cache_dir.mkdir(parents=True, exist_ok=True)
_datalab_cache_dir.mkdir(parents=True, exist_ok=True)

os.environ.setdefault("RAG_MODEL_CACHE_BASE_DIR", str(RAG_MODEL_CACHE_BASE_DIR))
os.environ.setdefault("HF_HOME", str(_hf_cache_dir))
os.environ.setdefault("TRANSFORMERS_CACHE", str(_hf_cache_dir))
os.environ.setdefault("TORCH_HOME", str(_torch_cache_dir))
os.environ.setdefault("MODEL_CACHE_DIR", str(_datalab_cache_dir))

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-me')
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# ==========================================
# 1. APPLICATION DEFINITION
# ==========================================
_HAS_UNFOLD = importlib.util.find_spec("unfold") is not None
_HAS_RANGEFILTER = importlib.util.find_spec("rangefilter") is not None

INSTALLED_APPS = [
    *(['unfold', 'unfold.contrib.filters'] if _HAS_UNFOLD else []),
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- LIBRARY PIHAK KETIGA ---
    'rest_framework',
    'inertia',
    'django_vite',
    'axes',
    *(["rangefilter"] if _HAS_RANGEFILTER else []),

    # --- APP ANDA ---
    'core',
]

UNFOLD = {
    "SITE_TITLE": "Academic Admin Portal",
    "SITE_HEADER": "Academic AI Administration",
    "SITE_SUBHEADER": "Command Center",
    "SITE_SYMBOL": "monitoring",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
        }
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',

    # ✅ Tambahan: Request ID + access log (tidak mengubah behavior endpoint)
    'core.middleware.RequestContextMiddleware',
    'core.middleware.UserPresenceMiddleware',
    'core.middleware.MaintenanceModeMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # WAJIB: Middleware Inertia (Taruh setelah Auth & Message)
    'inertia.middleware.InertiaMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# --- AXES (rate limit login) ---
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_COOLOFF_TIME = 0.05  # jam (~3 menit); bisa diubah via env
AXES_RESET_ON_SUCCESS = True
# Tampilkan username & IP di log axes (defaultnya dimask)
AXES_SENSITIVE_PARAMETERS = []

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Sumber utama template: core/templates (termasuk admin/*).
        # Folder templates tetap dipertahankan sebagai fallback.
        'DIRS': [BASE_DIR / 'core' / 'templates', BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==========================================
# 2. DATABASE & PASSWORD
# ==========================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ==========================================
# 3. INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta'
USE_I18N = True
USE_TZ = True


# ==========================================
# 4. STATIC FILES & VITE CONFIGURATION
# ==========================================
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

DJANGO_VITE_ASSETS_PATH = BASE_DIR / 'core' / 'static' / 'dist'
DJANGO_VITE_DEV_MODE = DEBUG
DJANGO_VITE_DEV_SERVER_PORT = 5173


# ==========================================
# 5. INERTIA CONFIGURATION
# ==========================================
INERTIA_LAYOUT = 'base.html'


# ==========================================
# 6. MEDIA FILES (UPLOAD)
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# 7. AUTHENTICATION REDIRECTS
# ==========================================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# ==========================================
# 8. LOGGING (FINAL: COLORED + RAPI + REQUEST ID + FILE:LINE)
# ==========================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "filters": {
        "request_id": {
            "()": "config.logging_filters.RequestIdFilter",
        },
    },

    "formatters": {
        "colored_pretty": {
            "()": "colorlog.ColoredFormatter",

            # Kolom dibuat fixed-width supaya rata:
            # - levelname: 8 char (INFO/WARNING/ERROR)
            # - logger name: 28 char (dipotong kalau kepanjangan)
            # - rid: 10 char
            # - location: filename:lineno funcName (tetap jelas)
            #
            # Catatan: %(name)-28s akan left-align dan auto truncate di terminal.
            # Layout umum: padat, cocok untuk terminal kecil (pakai '|')
            "format": (
                "%(log_color)s%(levelname)s%(reset)s|"
                "%(white)s%(asctime)s%(reset)s|"
                "%(cyan)s%(name)s%(reset)s|"
                "%(white)srid=%(request_id)s%(reset)s|"
                "%(blue)s%(method)s%(reset)s|"
                "%(white)s%(path)s%(reset)s|"
                "%(status_color)s%(status)s%(reset)s|"
                "%(yellow)s%(duration_ms)sms%(reset)s|"
                "%(white)suser=%(user)s%(reset)s|"
                "%(white)sip=%(ip)s%(reset)s|"
                "%(white)sua=%(agent)s%(reset)s|"
                "%(white)src=%(referer)s%(reset)s|"
                "%(purple)s%(filename)s:%(lineno)d%(reset)s|"
                "%(message)s\n"
            ),
            "datefmt": "%H:%M:%S",

            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "red,bg_white",
            },
            "reset": True,
        },
        "request_compact": {
            "()": "colorlog.ColoredFormatter",
            # Layout akses log: sangat padat, pakai '|'
            "format": (
                "%(log_color)s%(levelname)s%(reset)s|"
                "%(white)s%(asctime)s%(reset)s|"
                "%(blue)s%(method)s%(reset)s|"
                "%(white)s%(path)s%(reset)s|"
                "%(status_color)s%(status)s%(reset)s|"
                "%(yellow)s%(duration_ms)sms%(reset)s|"
                "%(white)suser=%(user)s%(reset)s|"
                "%(white)sip=%(ip)s%(reset)s|"
                "%(white)srid=%(request_id)s%(reset)s|"
                "%(white)sua=%(agent)s%(reset)s|"
                "%(white)src=%(referer)s%(reset)s\n"
            ),
            "datefmt": "%H:%M:%S",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "red,bg_white",
            },
            "reset": True,
        },
        "audit_plain": {
            "format": "%(asctime)s|%(levelname)s|rid=%(request_id)s|user=%(user)s|ip=%(ip)s|%(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "app_plain": {
            # Format rinci seperti access log terminal:
            # INFO|17:33:02|GET|/path|200|3ms|user=...|ip=...|rid=...|ua=...|rc=...
            "format": (
                "%(levelname)s|%(asctime)s|%(method)s|%(path)s|%(status)s|%(duration_ms)sms|"
                "user=%(user)s|ip=%(ip)s|rid=%(request_id)s|ua=%(agent)s|rc=%(referer)s|%(message)s"
            ),
            "datefmt": "%H:%M:%S",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "colored_pretty",
            "filters": ["request_id"],
            "level": "DEBUG" if DEBUG else "INFO",
        },
        "console_request": {
            "class": "logging.StreamHandler",
            "formatter": "request_compact",
            "filters": ["request_id"],
            "level": "INFO",
        },
        "audit_file": {
            # Windows-safe rotating handler (hindari file lock error)
            "class": "concurrent_log_handler.ConcurrentTimedRotatingFileHandler",
            "filename": str(LOG_DIR / "audit.log"),
            "when": "midnight",
            "backupCount": 14,
            "encoding": "utf-8",
            "delay": True,
            "formatter": "audit_plain",
            "filters": ["request_id"],
            "level": "INFO",
        },
        "app_file": {
            "class": "concurrent_log_handler.ConcurrentTimedRotatingFileHandler",
            "filename": str(LOG_DIR / "app.log"),
            "when": "midnight",
            "backupCount": 14,
            "encoding": "utf-8",
            "delay": True,
            "formatter": "app_plain",
            "filters": ["request_id"],
            "level": "INFO",
        },
    },

    "loggers": {
        # Root logger: semua log default masuk sini
        "": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
        },

        # Access log 1 baris per request (dari middleware kamu)
        "request": {
            "handlers": ["console_request", "app_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Hindari log dobel akses dari Django server
        # (kamu sudah punya access log dari "request")
        "django.server": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },

        # Error request Django (500)
        "django.request": {
            "handlers": ["console", "app_file"],
            "level": "ERROR",
            "propagate": False,
        },

        # Inertia cukup WARNING
        "inertia": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },

        # AI engine: INFO (kalau mau super detail: ganti jadi DEBUG)
        "core.ai_engine": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },

        # Audit log untuk aksi penting (disimpan di file + tampil di terminal)
        "audit": {
            "handlers": ["console", "audit_file", "app_file"],
            "level": "INFO",
            "propagate": False,
        },

        # (Opsional) Supaya log httpx/chroma tidak terlalu “berisik”
        "httpx": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "chromadb": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },
        "chromadb.telemetry": {
            "handlers": ["console", "app_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
